Fix build issues
grpc/test-infra pull request #393
Opened 2024-03-11 19:33 UTC by fdfzcq

Same fix as https://github.com/GoogleCloudPlatform/gke-managed-certs/commit/fa3e1a4b5f12502f4396e8810ccf2370eae42348

Installation of gcloud SDK fails when building driver image:

```
 => ERROR [stage-2 11/15] RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" |   tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && c  12.2s
------
 > [stage-2 11/15] RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" |   tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg |   apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y:
#26 0.243 deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main
#26 0.306   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#26 0.306                                  Dload  Upload   Total   Spent    Left  Speed
100  2659  100  2659    0     0   5318      0 --:--:-- --:--:-- --:--:--  5404
#26 0.835 Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
#26 1.069 OK
#26 1.559 Hit:1 http://deb.debian.org/debian bullseye InRelease
#26 1.559 Hit:2 http://deb.debian.org/debian-security bullseye-security InRelease
#26 1.575 Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
#26 1.930 Get:4 http://packages.cloud.google.com/apt cloud-sdk InRelease [1616 B]
#26 6.520 Err:5 http://packages.cloud.google.com/apt cloud-sdk/main amd64 Packages
#26 6.520   502  Bad Gateway [IP: 142.250.74.110 80]
#26 6.696 Err:6 http://packages.cloud.google.com/apt cloud-sdk/main all Packages
#26 6.696
#26 6.778 Fetched 1616 B in 5s (301 B/s)
#26 6.778 Reading package lists...
#26 9.053 W: Failed to fetch http://packages.cloud.google.com/apt/dists/cloud-sdk/main/binary-amd64/Packages  502  Bad Gateway [IP: 142.250.74.110 80]
#26 9.054 W: Failed to fetch http://packages.cloud.google.com/apt/dists/cloud-sdk/main/binary-all/Packages
#26 9.054 W: Some index files failed to download. They have been ignored, or old ones used instead.
#26 9.170 Reading package lists...
#26 11.46 Building dependency tree...
#26 11.92 Reading state information...
#26 12.21 E: Unable to locate package google-cloud-sdk
```

2024-03-13 21:29 UTC, paulosjca approved these changes

2024-03-14 07:21 UTC, paulosjca requested changes
The package name has changed for newer releases. I would take the command from the location below (with `google-cloud-cli` instead of `google-cloud-sdk`), and combine it into a single RUN command:

https://cloud.google.com/sdk/docs/install-sdk#deb

The end result would be something like this:

```dockerfile
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | \
  tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
  curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
  gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg && \
  apt-get update -y && apt-get install google-cloud-cli -y
```

2024-03-18 09:42 UTC, fdfzcq commented
Thank you! @paulosjca I made a fix now

2024-03-18 09:48 UTC, paulosjca approved these changes

2024-03-18 09:55 UTC, merged